monitor = desc:Acer Technologies Acer XB271H, 1920x1080@143.98, -1080x0, 1, transform, 1
monitor = desc:Samsung Electric Company Odyssey G85SB H1AK50000, 3440x1440@119.96, 0x0, 1
monitor = , preferred, auto, 1

# Only one workspace on second monitor, otherwise it is confusing
workspace = 9, name:side, monitor:Acer Technologies Acer XB271H, default:true, on-created-empty:discord, persistent:true

# Multiple workspaces on main monitor
workspace = 1, name:main, monitor:desc:Samsung Electric Company Odyssey G85SB H1AK500000, on-created-empty:gimp, persistent:true

workspace = 2, monitor:desc:Samsung Electric Company Odyssey G85SB H1AK500000, on-created-empty:zen-browser, persistent:true

workspace = 3, monitor:desc:Samsung Electric Company Odyssey G85SB H1AK500000, default:true, on-created-empty:Alacritty, persistent:true

workspace = 4, monitor:desc:Samsung Electric Company Odyssey G85SB H1AK500000, persistent:true

workspace = 5, monitor:desc:Samsung Electric Company Odyssey G85SB H1AK500000, persistent:true

workspace = 6, monitor:desc:Samsung Electric Company Odyssey G85SB H1AK500000, persistent:true

workspace = 7, monitor:desc:Samsung Electric Company Odyssey G85SB H1AK500000, persistent:true

workspace = 8, monitor:desc:Samsung Electric Company Odyssey G85SB H1AK500000, persistent:true

workspace = 0, monitor:desc:Samsung Electric Company Odyssey G85SB H1AK500000, persistent:true
