# Monitor setup
monitor = , preferred, auto, 1

# Multiple workspaces on main monitor
workspace = 1, persistent:true, name:main, on-created-empty:gimp

workspace = 2, persistent:true, on-created-empty:zen-browser

workspace = 3, persistent:true, default:true, on-created-empty:Alacritty

workspace = 4, persistent:true, on-created-empty:code

workspace = 5, persistent:true

workspace = 6, persistent:true

workspace = 7, persistent:true

workspace = 8, persistent:true

workspace = 9, on-created-empty:discord, persistent:true

workspace = 0, persistent:true

