hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("awww img ~/.config/hypr/hyprpaper/what-expanded.gif")
    hl.exec_cmd("hyprsunset 2>&1 > ~/hyprsunsetlog.txt")
    hl.exec_cmd("waybar")

    hl.exec_cmd("vesktop", { workspace = "10" })
    hl.exec_cmd("gimp", { workspace = "1" })
    hl.exec_cmd("chromium", { workspace = "3" })
    hl.exec_cmd("alacritty", { workspace = "2" })
    hl.exec_cmd("spotify-launcher", { workspace = "6" })
    hl.exec_cmd("obsidian", { workspace = "8" })
end)
