hl.on("hyprland.start", function()
    hl.exec_cmd("hypridle")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("awww img ~/.config/hypr/hyprpaper/what-expanded.gif")
    hl.exec_cmd("hyprsunset 2>&1 > ~/hyprsunsetlog.txt")
    hl.exec_cmd("waybar")

    hl.exec_cmd("discord", { workspace = "10", silent = true })
    hl.exec_cmd("gimp", { workspace = "1", silent = true })
    hl.exec_cmd("google-chrome-stable", { workspace = "2", silent = true })
    hl.exec_cmd("alacritty", { workspace = "3", silent = true })
    hl.exec_cmd("spotify-launcher", { workspace = "6", silent = true })
    hl.exec_cmd("obsidian", { workspace = "8", silent = true })
end)
